### ISSUE TITLE
Add an option to adjust line width

### ISSUE THREAD

**Issue by baruchavi** [Farid023/flutter_tournament_bracket#2]
I love this package so much! It is exactly what I needed for a project I am working on, one thing that would be so nice to have would be to be able to adjust the line width that connects each match card. I was looking around the code myself but I was unsure where to start. Such an amazing package!!

**Comment by baruchavi** [comment]
I figured it out, created a pull request with the change #3

**Comment by farid023** [comment]
Thank you so much for the kind words! 😊 I'm really glad to hear that the package is helpful for your project. I've already published a new version that includes the ability to adjust the line width, along with some other improvements. Feel free to check out the latest updates!

If you find the package useful, it would mean a lot to me if you could leave a like on Pub.dev and a star on the repository to help others discover it. Your support is greatly appreciated! ✨
